# Generated by Django 3.2.11 on 2023-07-20 20:36

import apps.home.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='creator',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(null=True, upload_to='static/assets/images/playlist_images/'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='spotifyLink',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(default=apps.home.models.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='youtubeLink',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='spotifyURI',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(null=True, upload_to='static/assets/images/song_images/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='writer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
