# Generated by Django 3.2.11 on 2023-07-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_update_user_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
        migrations.AddField(
            model_name='playlist',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
