# Generated by Django 3.2.11 on 2023-07-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230723_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image_url',
            field=models.URLField(default='https://community.spotify.com/t5/image/serverpage/image-id/25294i2836BD1C1A31BDF2?v=v2'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image_url',
            field=models.URLField(default='https://community.spotify.com/t5/image/serverpage/image-id/25294i2836BD1C1A31BDF2?v=v2'),
        ),
    ]
